### ISSUE TITLE
Not all EOL Packages Being Picked up

### ISSUE THREAD

**Issue by spencerrung** [xeol-io/xeol#102]
**What happened**:

Hello again! 
I have a container and or sbom of a container that has dotnet sdk 3.1 (which is eol) not being picked up by xeol.
ex from sbom
```"id": "b0c0f5f4681e563d",
   "name": "dotnet-sdk-3.1",
   "version": "3.1.426-1.el8_7",
   "type": "rpm",
   "foundBy": "rpm-db-cataloger",
```

 I am wondering if there is something not right with the support for rpm packages, the other error I got was

 `[0000]  WARN unknown package metadata type="DotnetPortableExecutableMetadata" for packageID="861efa353f20821b" form-lib=syft`

**What you expected to happen**:
Should identify dotnet 3.1 as EOL

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Output of `xeol version`:  0.6.0, 
Syft Version:         v0.83.1
- OS (e.g: `cat /etc/os-release` or similar): macos

**Comment by noqcks** [comment]
Hello! Does the SBOM you generate contain a PURL for the package `dotnet-sdk-3.1`, and if so, could you share the PURL?

**Comment by spencerrung** [comment]
Yup!
```"purl": "pkg:rpm/rhel/dotnet-sdk-3.1@3.1.426-1.el8_7?arch=x86_64&upstream=dotnet3.1-3.1.426-1.el8_7.src.rpm&distro=rhel-8.7"```

**Comment by noqcks** [comment]
Ahh, a very interesting PURL from rpm.... which includes the version in the package name...

I added a PR to endoflife.date [here](https://github.com/endoflife-date/endoflife.date/pull/3400) to add the PURLs necessary for a match.

**Comment by noqcks** [comment]
You very well may! EOL data fidelity is probably one of the biggest issues with xeol right now. There's unfortunately no single global source for all different variations of package PURLs. 

At a high level: we ingest data from endoflife.date every 24 hours and throw it into a sqlite3 database which is stored in s3 and then downloaded by the CLI. Each endoflife.data product should have PURLs associated with it just like in the PR linked. The meat of the matching logic in xeol for PURLs is located [here](https://github.com/xeol-io/xeol/blob/20ea3eae1b7070e71e28c7d039d3aefee1689d6c/xeol/search/purl.go). Once you clone the repo, you can just run `go run main.go <image>` to test

**Comment by witchcraze** [comment]
Hi, 

From google, "3.1.426-1.el8_7" may be provided from OS vendor/community.
If so, support period (EOL) will be defined by this page
https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle
![image](https://github.com/xeol-io/xeol/assets/67056980/c2a119ad-a767-4b2e-a84a-553d8b0a3845)

If not so, support period (EOL) will be defined by this page
https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core
![image](https://github.com/xeol-io/xeol/assets/67056980/843b90ea-61e3-4716-b110-6811b9e03c90)


Fortunatelly, Red Hat provides almost similar support period for dotnat as same as official support period.
But Red Hat sometimes provide long term support period -Full Life Application Streams-.

Then, I felt matching "purl: pkg:rpm/rhel/*" with "endoflife.date" will sometimes lead wrong judgement...

**Comment by noqcks** [comment]
Ah, another edge case! Thanks for providing this information @witchcraze 

The RHEL package EOLs is something that can't be supported by the endoflife.date data structure currently. I've been doing some thinking about a more extensible data format over [here](https://github.com/endoflife-date/endoflife.date/discussions/3346)

**Comment by noqcks** [comment]
[The PR above](https://github.com/endoflife-date/endoflife.date/pull/3400) has been merged in, so we should be able close this issue now. Please reopen if it's still not matching correctly.
