### ISSUE TITLE
Not finding EOL'ed versions of HAProxy

### ISSUE THREAD

**Issue by bisbell-ngc** [xeol-io/xeol#268]
Related to https://github.com/xeol-io/xeol/issues/266

Database is missing purl identifiers for haproxy.

Test using container image _haproxy:2.5.14_

purl entry  _pkg:generic/haproxy_ fixes the issue when using SBOM from Syft v0.93.0.

**Comment by noqcks** [comment]
Identifiers for haproxy have now been added to endoflife.date for haproxy, and xeol returns the correct finding for `haproxy:2.5.14`

```
$ xeol haproxy:2.5.14
 ✔ EOL DB                          [updated]
 ✔ Scanned for EOL                 [1 eol matches]
NAME     VERSION  EOL         DAYS EOL  TYPE
haproxy  2.5.14   2023-02-14  332       binary
```
