### ISSUE TITLE
[Request] Self Hosted Option

### ISSUE THREAD

**Issue by zero77** [xeol-io/xeol#276]
**What would you like to be added**:
Can you please give the option to self host the xeol server.

**Why is this needed**:
Some people may want or need to self host the server themselves.

**Additional context**:

**Comment by noqcks** [comment]
:wave: @zero77 

Could you clarify what you mean by self hosting the server? The CLI works fetches all EOL database information from S3 and  stores it locally before it runs a scan.

Do you mean self hosting https://www.xeol.io?
