### ISSUE TITLE
Allow configurable tmp dir for docker image load

### ISSUE THREAD

**Issue by navzen2000** [xeol-io/xeol#295]
**What would you like to be added**:
Need a configurable tmp directory to load image

**Why is this needed**:
1 error occurred:
        * failed to catalog: unable to load image: unable to use DockerDaemon source: mkdir /tmp/scope-386: no space left on device

**Additional context**:

**Comment by noqcks** [comment]
https://github.com/xeol-io/xeol-action/issues/30

we need to add this to the documentation, but you can use TMPDIR to specify the tmp dir to load the image
