### ISSUE TITLE
copying xeol to `/usr/local/bin` would need root privileges 

### ISSUE THREAD

**Issue by thebigbone** [xeol-io/xeol#345]
Hello, I noticed that the recommended one liner script gives `permission denied` error while installing at `/usr/local/bin` which is expected. I would suggest to add `sudo` at the beginning (`sudo sh -s -- -b /usr/local/bin`) to make sure the script has sufficient permission.

**Comment by noqcks** [comment]
would prefer to leave sudo out in the default command especially since it's executing an install script from the internet. I would recommend installing to a specific location and then sudo moving to /usr/local/bin if only root has access to /usr/local/bin

```
curl -sSfL https://raw.githubusercontent.com/xeol-io/xeol/main/install.sh | sh -s -- -b /tmp && sudo mv /tmp/xeol /usr/local/bin/xeol
```
