### ISSUE TITLE
json output not working

### ISSUE THREAD

**Issue by wer-anders** [xeol-io/xeol#60]
**What happened**:
When running `xeol mongo:3.2 -o json`, no json is shown. Instead the following error is thrown:
`[0002]  WARN unable to show catalog image finished event: unable to show eol report: unable to find package in collection: <nil>`

**What you expected to happen**:
json output

**How to reproduce it (as minimally and precisely as possible)**:
Install xeol Version 0.2.6 or newer and run `xeol mongo:3.2 -o json`

**Anything else we need to know?**:
With xeol Version 0.2.5 this is still working

**Environment**:
- Output of `xeol version`:

> Application:          xeol
> Version:              0.2.7
> Syft Version:         v0.77.0
> GitCommit:            1059a82f974122bce8498dec2adc5eefdca65100
> Platform:             linux/amd64
> GoVersion:            go1.18.10
> Compiler:             gc

**Comment by noqcks** [comment]
Hi @wer-anders 👋  sorry about this bug, I pushed a fix in [version 0.2.8](https://github.com/xeol-io/xeol/releases/tag/v0.2.8)
