### ISSUE TITLE
Add a pronunciation section to README for xeol

### ISSUE THREAD

**Issue by darinpope** [xeol-io/xeol#76]
**What would you like to be added**:
Add a pronunciation section to README for how to pronounce "xeol". 

**Why is this needed**:
Since it's not clear how to say "xeol", this would help anyone wanting to (a) create a video about how to use xeol or (b) talk about it on a podcast, etc. A few examples of how this is done in other repos:

* https://github.com/talkatv/talkatv
* https://github.com/eclarizio/pinakes

**Comment by noqcks** [comment]
hi @darinpope, thanks for creating an issue! we just added a pronunciation guide to the docs

https://github.com/xeol-io/xeol#pronunciation
