### ISSUE TITLE
Unexisting recommended option --add-cpes-if-none ?

### ISSUE THREAD

**Issue by AppSecAmael** [xeol-io/xeol#87]
**Before anything**:
I just discovered this tool, thanks a lot for your work ! 

**What happened**:
In my first tests I scanned a SBOM that uses purl specifications and not CPEs, and got the following message :
```
[0000]  WARN some package(s) are missing CPEs. This may result in missing vulnerabilities. You may autogenerate these using: --add-cpes-if-none
```

So I tried to add it, but the option is not recognized.... 
```
$ cat my-sbom.json | xeol --add-cpes-if-none
unknown flag: --add-cpes-if-none
``` 

**What you expected to happen**:
Well, either the option does not exist and you don't recommend to use it, or you implement the option :)

**How to reproduce it (as minimally and precisely as possible)**:
Remove CPEs from a SBOM and run the analysis using `cat my-sbom.json | xeol --add-cpes-if-none`

**Environment**:
- Output of `xeol version`: 
```
Application:          xeol
Version:              0.4.6
Syft Version:         v0.83.1
GitCommit:            4453938de9bf10780da6c9244201720ef6b6cf8b
Platform:             linux/amd64
GoVersion:            go1.18.10
Compiler:             gc
```

- OS (e.g: `cat /etc/os-release` or similar):
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2023.1"
VERSION_ID="2023.1"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

**Comment by noqcks** [comment]
Hi Amael, thanks for the report! This looks like a false warning that's a remnant of the porting most of the codebase from grype. 

We match two different things in Xeol, packages derived from Syft, and Distro/OS also generated by syft. 
- PURLs are used for packages, to match pacakges to EOL software from endoflife.date. [[example](https://raw.githubusercontent.com/endoflife-date/endoflife.date/master/products/mongodb.md)]
- CPEs are used to match OS's (there is no support for "OS" in the PURL spec). [[example](https://raw.githubusercontent.com/endoflife-date/endoflife.date/master/products/alpinelinux.md)]

We should actually have some kind of warning that says `some package(s) are missing PURLs` here, and remove the warning about missing CPEs for now. Potentially xeol supports CPE matching with endoflife.date for packages in the future, but for now there is none.

**Comment by noqcks** [comment]
This confusing warning message has since been removed. We weren't using CPEs in this manner for matching. Closing this issue.

**Comment by noqcks** [comment]
This confusing warning message has since been removed. We weren't using CPEs in this manner for matching. Closing this issue.
