### ISSUE TITLE
DB import cmd seems to be missing from cli

### ISSUE THREAD

**Issue by spencerrung** [xeol-io/xeol#98]
**What happened**:
Attempted to run `xeol db import`

**What you expected to happen**:
It to be imported based on the readme https://github.com/xeol-io/xeol#:~:text=xeol%20db%20import%20%E2%80%94%20provide%20xeol%20with%20a%20database%20archive%20to%20explicitly%20use%20(useful%20for%20offline%20DB%20updates)

**How to reproduce it (as minimally and precisely as possible)**:
`xeol db import`
**Anything else we need to know?**:

**Environment**:
- Output of `xeol version`:  0.5.0
- OS (e.g: `cat /etc/os-release` or similar): macos/alpine

**Comment by noqcks** [comment]
Hi, thanks for reporting this! I just added a db import command in #99. 

Going to release a new minor version shortly.

**Comment by spencerrung** [comment]
Well that was amazingly fast! Much appreciated 🎉

**Comment by noqcks** [comment]
No problem! Happy to please!

This will be available in v0.6.0, should be available in about 30 mins once CI tasks finish.
